import { toggleAttendanceDay, toggleFamilyAttendanceDay } from "@/app/actions";
import { enumerateDates, formatJalaliDate, formatPersianWeekday, toLocalDate } from "@/lib/date";
import { isPresent } from "@/services/attendance";
import { AttendanceCheckbox } from "./attendance-checkbox";
import { FamilyDisclosure } from "./family-disclosure";

type TimelineFamily = { id: string; name: string; persons: { id: string; name: string; attendancePeriods: { startDate: Date; endDate: Date }[] }[] };

export function Timeline({ tripId, startDate, endDate, families, hasExpenses }: { tripId: string; startDate: Date; endDate: Date; families: TimelineFamily[]; hasExpenses: boolean }) {
  const days = enumerateDates(startDate, endDate);
  const warning = "این تغییر روی هزینه‌های ثبت‌شده اثر می‌گذارد. آیا سهم هزینه‌های مرتبط دوباره محاسبه شود؟";

  return <section className="mt-10"><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-emerald-700">روزهای سفر</p><h2 className="mt-1 text-2xl font-black">خط زمانی حضور</h2><p className="mt-2 text-sm text-slate-500">خانواده‌ها به‌صورت بسته نمایش داده می‌شوند. تیک هر روز، حضور همه اعضای خانواده را تعیین می‌کند؛ برای استثناها خانواده را باز کنید.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-sm font-bold text-emerald-800">{days.length.toLocaleString("fa-IR")} روز</span></div>
    <div className="overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm" role="region" aria-label="خط زمانی حضور اعضا" tabIndex={0}><div className="min-w-max">
      <div className="sticky top-0 z-20 flex border-b border-slate-200 bg-white"><div className="sticky right-0 z-30 w-40 shrink-0 border-l border-slate-200 bg-white px-4 py-3 font-bold">خانواده یا عضو</div>{days.map((day, index) => <div key={toLocalDate(day)} className="w-14 shrink-0 px-1 py-3 text-center text-xs"><strong className="block text-slate-900">{(index + 1).toLocaleString("fa-IR")}</strong><span className="mt-1 block font-bold text-slate-700">{formatPersianWeekday(day)}</span><span className="mt-1 block text-slate-500">{formatJalaliDate(day).split(" ").slice(0, 2).join(" ")}</span><span className="mt-1 block text-[10px] text-emerald-700">{families.flatMap((family) => family.persons).filter((person) => isPresent(person.attendancePeriods, day)).length.toLocaleString("fa-IR")} نفر</span></div>)}</div>
      {families.map((family) => <FamilyDisclosure key={family.id} name={family.name} memberCount={family.persons.length} headerDays={<>{days.map((day) => { const presentCount = family.persons.filter((person) => isPresent(person.attendancePeriods, day)).length; const checked = family.persons.length > 0 && presentCount === family.persons.length; const indeterminate = presentCount > 0 && !checked; const label = `${family.name} در ${formatJalaliDate(day)} ${checked ? "حاضر" : indeterminate ? "حضور متفاوت" : "غایب"} است؛ برای تغییر همه اعضا بزنید`; return <AttendanceCheckbox key={toLocalDate(day)} action={toggleFamilyAttendanceDay.bind(null, tripId, family.id, toLocalDate(day))} checked={checked} indeterminate={indeterminate} confirmMessage={hasExpenses ? warning : undefined} label={label} />; })}</>}><div>{family.persons.map((person) => <div key={person.id} className="flex border-t border-slate-100"><div className="sticky right-0 z-10 flex w-40 shrink-0 items-center border-l border-slate-200 bg-white px-4"><span className="max-w-28 truncate text-sm font-bold">{person.name}</span><span className="mr-2 text-xs text-slate-400">استثنا</span></div>{days.map((day) => { const checked = isPresent(person.attendancePeriods, day); const label = `${person.name} در ${formatJalaliDate(day)} ${checked ? "حاضر" : "غایب"} است؛ برای تغییر بزنید`; return <AttendanceCheckbox key={toLocalDate(day)} action={toggleAttendanceDay.bind(null, tripId, person.id, toLocalDate(day))} checked={checked} confirmMessage={hasExpenses ? warning : undefined} label={label} />; })}</div>)}</div></FamilyDisclosure>)}
    </div></div>
  </section>;
}
