import Link from "next/link";
import { notFound } from "next/navigation";
import { createPayment, deletePayment } from "@/app/actions";
import { DeleteButton } from "@/components/delete-button";
import { ErrorBanner } from "@/components/error-banner";
import { Field, fieldClass } from "@/components/field";
import { SubmitButton } from "@/components/submit-button";
import { TripNav } from "@/components/trip-nav";
import { formatJalaliDate, toLocalDate } from "@/lib/date";
import { formatMoney, fromRial } from "@/lib/money";
import { prisma } from "@/lib/prisma";
import { calculateFamilyBalances, calculatePersonBalances } from "@/services/balance";
import { generateSettlementSuggestions } from "@/services/settlement";
import { PersianDatePicker } from "@/components/persian-date-picker";
import { MoneyInput } from "@/components/money-input";

function Status({ balance, unit }: { balance: bigint; unit: "RIAL" | "TOMAN" }) { if (balance === 0n) return <span className="font-bold text-emerald-700">تسویه‌شده</span>; return <span className={`font-black ${balance > 0n ? "text-emerald-700" : "text-rose-700"}`}>{balance > 0n ? "باید دریافت کند: " : "باید پرداخت کند: "}{formatMoney(balance < 0n ? -balance : balance, unit)}</span>; }
const tabs = [{ key: "families", label: "خانواده‌ها" }, { key: "people", label: "افراد" }, { key: "suggestions", label: "پرداخت‌های پیشنهادی" }, { key: "payments", label: "پرداخت‌های ثبت‌شده" }];

export default async function SettlementPage({ params, searchParams }: { params: Promise<{ tripId: string }>; searchParams: Promise<{ view?: string; error?: string }> }) {
  const [{ tripId }, query] = await Promise.all([params, searchParams]); const view = query.view ?? "families";
  const trip = await prisma.trip.findUnique({ where: { id: tripId }, include: { families: { include: { persons: { orderBy: { createdAt: "asc" } } } }, persons: { orderBy: { createdAt: "asc" } }, payments: { orderBy: [{ paymentDate: "desc" }, { createdAt: "desc" }], include: { fromPerson: true, toPerson: true } } } }); if (!trip) notFound();
  const [people, families] = await Promise.all([calculatePersonBalances(tripId), calculateFamilyBalances(tripId)]); const suggestions = generateSettlementSuggestions(families.map((family) => ({ id: family.familyId, balanceRial: family.balanceRial }))); const totalRemaining = people.filter((person) => person.balanceRial > 0n).reduce((sum, person) => sum + person.balanceRial, 0n); const paymentDate = new Date() >= trip.startDate ? new Date() : trip.startDate;
  return <main className="mx-auto min-h-screen w-full max-w-5xl px-4 py-6 pb-24 sm:px-6 lg:pb-6"><TripNav tripId={trip.id} active="settlement" /><header className="mb-6"><h1 className="text-3xl font-black">تسویه {trip.name}</h1><p className="mt-2 text-slate-500">پرداخت‌ها و سهم واقعی هر نفر و خانواده</p></header><ErrorBanner message={query.error} />
    <div className={`mb-6 rounded-3xl p-5 ${totalRemaining === 0n ? "bg-emerald-100 text-emerald-900" : "bg-slate-900 text-white"}`}><strong className="text-lg">{totalRemaining === 0n ? "همه حساب‌ها تسویه شده‌اند" : `مانده کل: ${formatMoney(totalRemaining, trip.displayUnit)}`}</strong></div>
    <div className="mb-6 grid grid-cols-2 gap-1 rounded-2xl bg-slate-100 p-1 sm:grid-cols-4">{tabs.map((tab) => <Link key={tab.key} href={`?view=${tab.key}`} className={`rounded-xl p-3 text-center text-sm font-bold ${view === tab.key ? "bg-white shadow-sm" : "text-slate-500"}`}>{tab.label}</Link>)}</div>
    {view === "people" && <section className="grid gap-4 sm:grid-cols-2">{people.map((person) => <article key={person.personId} className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">{person.personName}</h2><p className="mt-3 text-sm">پرداخت‌شده: {formatMoney(person.paidRial, trip.displayUnit)} · سهم: {formatMoney(person.shareRial, trip.displayUnit)}</p><div className="mt-4"><Status balance={person.balanceRial} unit={trip.displayUnit} /></div></article>)}</section>}
    {view === "families" && <section className="grid gap-4 sm:grid-cols-2">{families.map((family) => <article key={family.familyId} className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">{family.familyName}</h2><p className="mt-3 text-sm">پرداخت‌شده: {formatMoney(family.paidRial, trip.displayUnit)} · سهم: {formatMoney(family.shareRial, trip.displayUnit)}</p><div className="mt-4"><Status balance={family.balanceRial} unit={trip.displayUnit} /></div></article>)}</section>}
    {view === "suggestions" && <section className="grid gap-6 lg:grid-cols-2"><div><h2 className="mb-4 text-xl font-black">تسویه خانوادگی</h2><div className="grid gap-4">{suggestions.map((suggestion, index) => { const from = trip.families.find((family) => family.id === suggestion.fromId)!; const to = trip.families.find((family) => family.id === suggestion.toId)!; return <article key={`${suggestion.fromId}-${index}`} className="rounded-3xl border border-slate-200 bg-white p-5"><p className="leading-8"><strong>{from.name}</strong> باید <strong>{formatMoney(suggestion.amountRial, trip.displayUnit)}</strong> به <strong>{to.name}</strong> پرداخت کند.</p><details className="mt-3"><summary className="cursor-pointer font-bold text-emerald-700">ثبت پرداخت</summary><form action={createPayment.bind(null, trip.id)} className="mt-4 grid gap-3"><Field label="پرداخت‌کننده"><select name="fromPersonId" defaultValue={from.persons[0]?.id} className={fieldClass}>{from.persons.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></Field><Field label="دریافت‌کننده"><select name="toPersonId" defaultValue={to.persons[0]?.id} className={fieldClass}>{to.persons.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></Field><Field label="واحد"><select name="unit" defaultValue={trip.displayUnit} className={fieldClass}><option value="TOMAN">تومان</option><option value="MILLION_TOMAN">میلیون تومان</option><option value="RIAL">ریال</option></select></Field><PersianDatePicker name="paymentDate" label="تاریخ پرداخت پیشنهادی" defaultValue={toLocalDate(paymentDate)} /><Field label="مبلغ (قابل تغییر برای پرداخت بخشی)"><MoneyInput defaultValue={fromRial(suggestion.amountRial, trip.displayUnit).toString()} /></Field><SubmitButton>ثبت پرداخت</SubmitButton></form></details></article>; })}{!suggestions.length && <p className="rounded-3xl bg-emerald-50 p-6 text-emerald-800">پیشنهاد پرداختی باقی نمانده است.</p>}</div></div>
      <div><h2 className="mb-4 text-xl font-black">ثبت دستی پرداخت</h2><form action={createPayment.bind(null, trip.id)} className="grid gap-4 rounded-3xl border border-slate-200 bg-white p-5"><Field label="از"><select name="fromPersonId" className={fieldClass}>{trip.persons.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></Field><Field label="به"><select name="toPersonId" defaultValue={trip.persons[1]?.id} className={fieldClass}>{trip.persons.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="مبلغ"><MoneyInput required /></Field><Field label="واحد"><select name="unit" defaultValue={trip.displayUnit} className={fieldClass}><option value="TOMAN">تومان</option><option value="MILLION_TOMAN">میلیون تومان</option><option value="RIAL">ریال</option></select></Field></div><Field label="تاریخ"><PersianDatePicker name="paymentDate" label="تاریخ پرداخت" defaultValue={toLocalDate(paymentDate)} /></Field><Field label="توضیحات اختیاری"><input name="description" maxLength={200} className={fieldClass} /></Field><SubmitButton>ثبت پرداخت</SubmitButton></form></div></section>}
    {view === "payments" && <section><h2 className="mb-4 text-xl font-black">تاریخچه پرداخت‌ها</h2><div className="grid gap-3">{trip.payments.map((payment) => <article key={payment.id} className="flex items-center justify-between gap-4 rounded-3xl border border-slate-200 bg-white p-5"><div><p><strong>{payment.fromPerson.name}</strong> به <strong>{payment.toPerson.name}</strong> {formatMoney(payment.amountRial, trip.displayUnit)} پرداخت کرد.</p><p className="mt-1 text-sm text-slate-500">{formatJalaliDate(payment.paymentDate)}{payment.description ? ` · ${payment.description}` : ""}</p></div><DeleteButton action={deletePayment.bind(null, trip.id, payment.id)} message="این پرداخت حذف شود؟" /></article>)}{!trip.payments.length && <p className="rounded-3xl border border-dashed border-slate-300 p-10 text-center text-slate-500">هنوز پرداختی ثبت نشده است.</p>}</div></section>}
  </main>;
}








